"""
DAY 1: Your First LangGraph Agent
===================================

WHAT WE'RE BUILDING:
A simple agent that takes a topic and generates research questions

CONCEPTS YOU'LL LEARN:
1. How to define state (shared data structure)
2. How to create agent functions (nodes)
3. How to connect agents (edges)
4. How to run the workflow locally

"""

# Import required libraries
from anthropic import Anthropic # type: ignore
from typing import TypedDict, List
from langgraph.graph import StateGraph, END # type: ignore
import os
from dotenv import load_dotenv # type: ignore

load_dotenv()

# ============================================================================
# PART 1: Define State (The "Ball" Being Passed Around)
# ============================================================================

class ResearchState(TypedDict):
    """
    This is your state schema - the data structure that flows through agents.
    
    Think of it like a form that gets filled out step by step:
    - User provides 'topic'
    - Planning agent adds 'research_questions'
    - Each agent updates 'current_step' to track progress
    """
    topic: str                    # User's input (e.g., "AI in healthcare")
    research_questions: List[str] # Questions generated by planner
    current_step: str            # Track which step we're on
    summary: str                 # Summary generated by summary agent

# ============================================================================
# PART 2: Initialize Claude Client
# ============================================================================

# Create Anthropic client for calling Claude
client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

print("Anthropic client initialized")

# ============================================================================
# PART 3: Define Agent Functions (Nodes)
# ============================================================================

def planning_agent(state: ResearchState) -> ResearchState:
    """
    AGENT #1: Planning Agent
    
    INPUT: ResearchState with 'topic' filled in
    OUTPUT: ResearchState with 'research_questions' added
    
    This function is a "node" in our graph.
    """
    
    print("\n" + "="*60)
    print("PLANNING AGENT: Generating research questions...")
    print("="*60)
    print(f"Topic: {state['topic']}\n")
    
    # Call Claude to generate questions
    message = client.messages.create(
        model="claude-sonnet-4-20250514",  # Latest Sonnet model
        max_tokens=1024,  # Max length of response
        messages=[{
            "role": "user",
            "content": f"""You are a research planning expert.

Topic: {state['topic']}

Generate exactly 3 specific, focused research questions that would help 
someone create a comprehensive report on this topic.

Format your response as a simple numbered list:
1. First question?
2. Second question?
3. Third question?"""
        }]
    )
    
    # Extract text from Claude's response
    # Claude returns a list of content blocks, we want the first one's text
    response_text = message.content[0].text
    
    print("Claude's response:")
    print(response_text)
    
    # Parse the numbered list into a Python list
    # Split by newlines, keep only lines that start with numbers
    questions = []
    for line in response_text.split('\n'):
        line = line.strip()
        # Check if line starts with a digit (1., 2., etc.)
        if line and line[0].isdigit():
            # Remove the number prefix (e.g., "1. " from "1. What is X?")
            question = line.split('. ', 1)[1] if '. ' in line else line
            questions.append(question)
    
    print(f"\nGenerated {len(questions)} questions")
    for i, q in enumerate(questions, 1):
        print(f"   {i}. {q}")
    
    # Update state with new information
    state['research_questions'] = questions
    state['current_step'] = 'planning_complete'
    
    # Return modified state
    return state

def summary_agent(state: ResearchState) -> ResearchState:
    """
    AGENT #2: Summary Agent
    
    INPUT: ResearchState with 'research_questions' filled in
    OUTPUT: ResearchState with 'summary' added
    
    This agent creates an executive summary of the research plan.
    """
    
    print("\n" + "="*60)
    print("📝 SUMMARY AGENT: Creating research summary...")
    print("="*60 + "\n")
    
    # Format questions for Claude
    questions_text = "\n".join([
        f"{i}. {q}" 
        for i, q in enumerate(state['research_questions'], 1)
    ])
    
    # Call Claude
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=512,
        messages=[{
            "role": "user",
            "content": f"""Based on these research questions:

{questions_text}

Write a brief 2-3 sentence executive summary explaining what this 
research will investigate and why it matters."""
        }]
    )
    
    summary = message.content[0].text
    
    print("Generated summary:")
    print(summary)
    print()
    
    # Add summary to state
    state['summary'] = summary
    state['current_step'] = 'complete'
    
    return state

# ============================================================================
# PART 4: Build the Graph (Workflow)
# ============================================================================

def create_simple_workflow():
    """
    Create a LangGraph workflow.
    
    For Day 1, it's very simple:
    START → Planning Agent → END
    """
    
    print("\n🏗️  Building workflow graph...")
    
    # Step 1: Initialize the graph with our state type
    workflow = StateGraph(ResearchState)
    
    # Step 2: Add nodes (agents)
    # Syntax: add_node(name, function)
    workflow.add_node("planner", planning_agent)
    workflow.add_node("summarizer", summary_agent)
    
    # Step 3: Set entry point (where workflow starts)
    workflow.set_entry_point("planner")
    
    # Step 4: Add edge to END (finish after planning)
    # Syntax: add_edge(from_node, to_node)
    workflow.add_edge("planner", "summarizer")
    workflow.add_edge("summarizer", END)  # END is a special node that signifies completion
    
    # Step 5: Compile graph into runnable app
    app = workflow.compile()
    
    print("Workflow compiled (2 agents)\n")
    print("Flow: Planner -> Summarizer -> END\n")
    
    return app

# ============================================================================
# PART 5: Run the Agent
# ============================================================================

def run_research(topic: str):
    """
    Execute the research workflow
    
    Args:
        topic: The research topic (string)
    
    Returns:
        Final state after all agents have run
    """
    
    print("\n" + "="*60)
    print("🚀 STARTING RESEARCH WORKFLOW")
    print("="*60)
    
    # Create initial state (the starting "ball")
    initial_state = {
        "topic": topic,
        "research_questions": [],  # Empty, will be filled by planner
        "summary": "",             # Empty, will be filled by summarizer
        "current_step": "initialized"
    }
    
    # Get compiled workflow
    app = create_simple_workflow()
    
    # Run it! This executes all nodes in order
    # invoke() is synchronous - waits for completion
    final_state = app.invoke(initial_state)
    
    print("\n" + "="*60)
    print("✅ WORKFLOW COMPLETE")
    print("="*60)
    
    return final_state

# ============================================================================
# PART 6: Test It!
# ============================================================================

if __name__ == "__main__":
    # Run with a test topic
    result = run_research("Impact of large language models on software engineering")
    
    # Print final results
    print("\n" + "="*60)
    print("📋 FINAL RESULTS")
    print("="*60)
    print(f"\nTopic: {result['topic']}")
    print(f"Status: {result['current_step']}")
    print(f"\nGenerated Research Questions:")
    for i, question in enumerate(result['research_questions'], 1):
        print(f"  {i}. {question}")
    print(f"\nExecutive Summary:")
    print(f"{result['summary']}")
    print()